coverage:
  precision: 2
  round: down
  range: "50...80"
  status:
    project:
      default:
        target: 50%
    patch:
      service:
        target: 41.67%
        threshold: 0.01%
        flags:
          - service
      controller:
        target: auto
        flags:
          - controller 
  critical_files_paths:
    - src/services/*
    - src/controllers/*
    - src/models/*
          
codecov:
  require_ci_to_pass: yes
  notify:
    manual_trigger: true
    notify_error: true

github_checks: #does not work if flags are configured
    annotations: true

comment:
  layout: "newheader, diff, flags, components, files"
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: false        # [yes :: must have a base report to post]
  require_head: true       # [yes :: must have a head report to post]
  show_carryforward_flags: true 
  show_critical_paths: true #new option to labeled critical files
  hide_comment_details: true #collapse all the "detailed info" for the PR comment

profiling:
  critical_files_paths:
    - app/Services/*
    - resources/js/classes/*
    - app/Models/Charge.php
  
flags:
  service:
    carryforward: true
    paths: 
      - src/services
  controller:
    carryforward: true
    paths: 
      - src/controllers

component_management:
  individual_components:
    - component_id: "backend"
      name: "backend"
      flag_regexes: # List of lags to be included in the component.
        - "controller"
        - "service"

- name: Upload coverage reports to Codecov
  uses: codecov/codecov-action@v5
  with:
    token: ${{ secrets.CODECOV_TOKEN }}
    directory: ./backend/coverage 
    verbose: true