codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        # basic
        target: 90%
        threshold: 1%
        # advanced
        if_ci_failed: error
        if_not_found: success
    patch:
      default:
        # basic
        target: 90%
        threshold: 1%
        # advanced
        if_ci_failed: error
        if_not_found: success

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: yes
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no