name: Load Test

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: "Test type to run"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - upload
          - get-by-id
      load_pattern:
        description: "Load pattern"
        required: true
        default: "both"
        type: choice
        options:
          - both
          - fixed
          - ramping

jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install k6
        run: |
          echo "Installing required dependencies..."
          sudo apt-get update
          sudo apt-get install -y gnupg2 dirmngr

          echo "Adding k6 repository and installing k6..."
          curl -s https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6
          echo "k6 installation completed."

      - name: Prepare Test Directory
        run: |
          mkdir -p backend/tests/load

      - name: Run Upload Fixed Load Test
        if: github.event_name == 'push' || github.event.inputs.test_type == 'all' || (github.event.inputs.test_type == 'upload' && (github.event.inputs.load_pattern == 'both' || github.event.inputs.load_pattern == 'fixed'))
        run: |
          echo "Starting Upload Fixed Load Test..."
          k6 run -e LOAD_CLIENT_ID=${{ secrets.LOAD_CLIENT_ID }} -e LOAD_CLIENT_SECRET=${{ secrets.LOAD_CLIENT_SECRET }} -e API_BASE_URL=${{ secrets.API_BASE_URL }} backend/tests/load/upload-inv-fixed-load.mjs | tee backend/tests/load/upload-fixed-load-test.log || echo "Upload Fixed Load Test failed!"
          echo "Upload Fixed Load Test completed."

      - name: Run Upload Ramping Load Test
        if: github.event_name == 'push' || github.event.inputs.test_type == 'all' || (github.event.inputs.test_type == 'upload' && (github.event.inputs.load_pattern == 'both' || github.event.inputs.load_pattern == 'ramping'))
        run: |
          echo "Starting Upload Ramping Load Test..."
          k6 run -e LOAD_CLIENT_ID=${{ secrets.LOAD_CLIENT_ID }} -e LOAD_CLIENT_SECRET=${{ secrets.LOAD_CLIENT_SECRET }} -e API_BASE_URL=${{ secrets.API_BASE_URL }} backend/tests/load/upload-inv-ramping-load.mjs | tee backend/tests/load/upload-ramping-load-test.log || echo "Upload Ramping Load Test failed!"
          echo "Upload Ramping Load Test completed."

      - name: Run Get-By-ID Fixed Load Test
        if: github.event_name == 'push' || github.event.inputs.test_type == 'all' || (github.event.inputs.test_type == 'get-by-id' && (github.event.inputs.load_pattern == 'both' || github.event.inputs.load_pattern == 'fixed'))
        run: |
          echo "Starting Get-By-ID Fixed Load Test..."
          k6 run -e LOAD_CLIENT_ID=${{ secrets.LOAD_CLIENT_ID }} -e LOAD_CLIENT_SECRET=${{ secrets.LOAD_CLIENT_SECRET }} -e API_BASE_URL=${{ secrets.API_BASE_URL }} backend/tests/load/get-invoice-fixed-load.mjs | tee backend/tests/load/get-fixed-load-test.log || echo "Get-By-ID Fixed Load Test failed!"
          echo "Get-By-ID Fixed Load Test completed."

      - name: Run Get-By-ID Ramping Load Test
        if: github.event_name == 'push' || github.event.inputs.test_type == 'all' || (github.event.inputs.test_type == 'get-by-id' && (github.event.inputs.load_pattern == 'both' || github.event.inputs.load_pattern == 'ramping'))
        run: |
          echo "Starting Get-By-ID Ramping Load Test..."
          k6 run -e LOAD_CLIENT_ID=${{ secrets.LOAD_CLIENT_ID }} -e LOAD_CLIENT_SECRET=${{ secrets.LOAD_CLIENT_SECRET }} -e API_BASE_URL=${{ secrets.API_BASE_URL }} backend/tests/load/get-invoice-ramping-load.mjs | tee backend/tests/load/get-ramping-load-test.log || echo "Get-By-ID Ramping Load Test failed!"
          echo "Get-By-ID Ramping Load Test completed."

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: load-test-results
          path: backend/tests/load/*.log
