name: Manual Migration and Seeding
on:
  workflow_dispatch:
    inputs:
      operation:
        description: 'Type of operation'
        required: true
        type: choice
        options:
          - migrate
          - rollback_migration
          - seed
          - undo_seed
      migration_name:
        description: 'Migration file name (optional)'
        required: false
        default: ''
      seeder_table:
        description: 'Table to seed (optional, default all)'
        required: false
        type: choice
        options:
          - all
          - partner
          - invoice
          - purchase_order
          - customer
          - vendors
          - items
        default: 'all'

jobs:
  migrate:
    if: ${{ github.event.inputs.operation == 'migrate' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Run Migrate
        env:
          MIGRATION_NAME: ${{ github.event.inputs.migration_name }}
        run: |
          if [ -z "$MIGRATION_NAME" ]; then
            npx sequelize-cli db:migrate
          else
            npx sequelize-cli db:migrate --to $MIGRATION_NAME
          fi

  rollback_migration:
    if: ${{ github.event.inputs.operation == 'rollback_migration' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Run Rollback Migration
        env:
          MIGRATION_NAME: ${{ github.event.inputs.migration_name }}
        run: |
          if [ -z "$MIGRATION_NAME" ]; then
            npx sequelize-cli db:migrate:undo:all
          else
            npx sequelize-cli db:migrate:undo --to $MIGRATION_NAME
          fi

  seed:
    if: ${{ github.event.inputs.operation == 'seed' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Run Seed
        env:
          SEEDER_TABLE: ${{ github.event.inputs.seeder_table }}
        run: |
          case "$SEEDER_TABLE" in
            all) npx sequelize-cli db:seed:all ;; 
            partner) npx sequelize-cli db:seed:all --seed 20250307134936-seed-partner.js ;; 
            invoice) npx sequelize-cli db:seed:all --seed 20250307135227-seed-invoice.js ;; 
            purchase_order) npx sequelize-cli db:seed:all --seed 20250309094054-seed-purchase-order.js ;; 
            customer) npx sequelize-cli db:seed:all --seed 20250309164526-seed-customer.js && npx sequelize-cli db:seed:all --seed 20250309164541-update-documents-with-customer.js ;; 
            vendors) npx sequelize-cli db:seed:all --seed 20250310013133-seed-vendors.js && npx sequelize-cli db:seed:all --seed 20250310013229-update-documents-with-vendor.js ;; 
            items) npx sequelize-cli db:seed:all --seed 20250312180204-create-items-and-associations.js ;; 
            *) echo "Unknown seeder table: $SEEDER_TABLE"; exit 1;;
          esac