name: Manual Migration and Seeding
on:
  workflow_dispatch:
    inputs:
      operation:
        description: 'Type of operation'
        required: true
        type: choice
        options:
          - migrate
          - rollback_migration
          - seed
          - undo_seed
      migration_name:
        description: 'Migration file name (optional)'
        required: false
        default: ''
      seeder_table:
        description: 'Table to seed (optional, default all)'
        required: false
        type: choice
        options:
          - all
          - partner
          - invoice
          - purchase_order
          - customer
          - vendors
          - items
        default: 'all'

jobs:
  setup:
    name: Setup SSH
    runs-on: ubuntu-latest
    outputs:
      ssh-key-path: ${{ steps.prepare-key.outputs.key-path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set branch name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Prepare SSH key
        id: prepare-key
        run: |
          echo "${{ secrets.SSH_KEY }}" > ssh-key.pem
          chmod 400 ssh-key.pem
          echo "::set-output name=key-path::ssh-key.pem"

      - name: Upload SSH key
        uses: actions/upload-artifact@v4
        with:
          name: ssh-key
          path: ssh-key.pem

      - name: Prepare remote environment
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh-key.pem \
            ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} \
              "cd ~/fin-invoice-ocr-team6/backend && git fetch origin && git reset --hard origin/$BRANCH_NAME && npm ci"

  migrate:
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.operation == 'migrate' }}
    steps:
      - name: Download SSH key
        uses: actions/download-artifact@v4
        with:
          name: ssh-key
          path: .
      - name: Set SSH key permission
        run: chmod 400 ssh-key.pem

      - name: Run Migrate
        env:
          MIGRATION_NAME: ${{ github.event.inputs.migration_name }}
        run: |
          if [ -z "$MIGRATION_NAME" ]; then
            CMD="npx sequelize-cli db:migrate"
          else
            CMD="npx sequelize-cli db:migrate --to $MIGRATION_NAME"
          fi
          ssh -o StrictHostKeyChecking=no -i ssh-key.pem ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} \
            "cd ~/fin-invoice-ocr-team6/backend && $CMD"

  rollback_migration:
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.operation == 'rollback_migration' }}
    steps:
      - name: Download SSH key
        uses: actions/download-artifact@v4
        with:
          name: ssh-key
          path: .
      - name: Set SSH key permission
        run: chmod 400 ssh-key.pem

      - name: Run Rollback Migration
        env:
          MIGRATION_NAME: ${{ github.event.inputs.migration_name }}
        run: |
          if [ -z "$MIGRATION_NAME" ]; then
            CMD="npx sequelize-cli db:migrate:undo:all"
          else
            CMD="npx sequelize-cli db:migrate:undo --to $MIGRATION_NAME"
          fi
          ssh -o StrictHostKeyChecking=no -i ssh-key.pem ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} \
            "cd ~/fin-invoice-ocr-team6/backend && $CMD"

  seed:
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.operation == 'seed' }}
    steps:
      - name: Download SSH key
        uses: actions/download-artifact@v4
        with:
          name: ssh-key
          path: .
      - name: Set SSH key permission
        run: chmod 400 ssh-key.pem

      - name: Run Seed
        env:
          SEEDER_TABLE: ${{ github.event.inputs.seeder_table }}
        run: |
          case "$SEEDER_TABLE" in
            all) CMD="npx sequelize-cli db:seed:all" ;; 
            partner) CMD="npx sequelize-cli db:seed --seed 20250307134936-seed-partner.js" ;; 
            invoice) CMD="npx sequelize-cli db:seed --seed 20250307135227-seed-invoice.js" ;; 
            purchase_order) CMD="npx sequelize-cli db:seed --seed 20250309094054-seed-purchase-order.js" ;; 
            customer) CMD="npx sequelize-cli db:seed --seed 20250309164526-seed-customer.js && npx sequelize-cli db:seed --seed 20250309164541-update-documents-with-customer.js" ;; 
            vendors) CMD="npx sequelize-cli db:seed --seed 20250310013133-seed-vendors.js && npx sequelize-cli db:seed --seed 20250310013229-update-documents-with-vendor.js" ;; 
            items) CMD="npx sequelize-cli db:seed --seed 20250312180204-create-items-and-associations.js" ;; 
            *) echo "Unknown seeder table: $SEEDER_TABLE"; exit 1;;
          esac
          ssh -o StrictHostKeyChecking=no -i ssh-key.pem ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} \
            "cd ~/fin-invoice-ocr-team6/backend && $CMD"

  undo_seed:
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.operation == 'undo_seed' }}
    steps:
      - name: Download SSH key
        uses: actions/download-artifact@v4
        with:
          name: ssh-key
          path: .
      - name: Set SSH key permission
        run: chmod 400 ssh-key.pem

      - name: Run Undo Seed
        env:
          SEEDER_TABLE: ${{ github.event.inputs.seeder_table }}
        run: |
          case "$SEEDER_TABLE" in
            all) CMD="npx sequelize-cli db:seed:undo:all" ;; 
            partner) CMD="npx sequelize-cli db:seed:undo --seed 20250307134936-seed-partner.js" ;; 
            invoice) CMD="npx sequelize-cli db:seed:undo --seed 20250307135227-seed-invoice.js" ;; 
            purchase_order) CMD="npx sequelize-cli db:seed:undo --seed 20250309094054-seed-purchase-order.js" ;; 
            customer) CMD="npx sequelize-cli db:seed:undo --seed 20250309164541-update-documents-with-customer.js && npx sequelize-cli db:seed:undo --seed 20250309164526-seed-customer.js" ;; 
            vendors) CMD="npx sequelize-cli db:seed:undo --seed 20250310013229-update-documents-with-vendor.js && npx sequelize-cli db:seed:undo --seed 20250310013133-seed-vendors.js" ;; 
            items) CMD="npx sequelize-cli db:seed:undo --seed 20250312180204-create-items-and-associations.js" ;; 
            *) echo "Unknown seeder table: $SEEDER_TABLE"; exit 1;;
          esac
          ssh -o StrictHostKeyChecking=no -i ssh-key.pem ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} \
            "cd ~/fin-invoice-ocr-team6/backend && $CMD"